FROM node:22.16.0-alpine3.22 AS builder
RUN mkdir app
WORKDIR /app
COPY package.json package.json
RUN node -v
RUN npm install --force
COPY ./client/. .
RUN npm run build



FROM node:22.16.0-alpine3.22  AS runner
WORKDIR /app
# ENV NODE_ENV=production
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
RUN ls -a
EXPOSE 3005
CMD ["npm", "run", "dev"]