services:
  pathfinder_mysql: 
    image: mysql:latest
    container_name: pathfinder_mysql
    environment:
      MYSQL_DATABASE: pathfinder_db
    env_file: .env
    ports:
      - "3306:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=temporary_root --execute \"SHOW DATABASES;\""
      timeout: 20s
      retries: 10
    #volumes:
      #- mysql_data:/var/lib/mysql
#volumes:
  #mysql_data:
    
  liquibase:
    image: liquibase/liquibase:latest
    depends_on: 
      pathfinder_mysql:
        condition: 
         service_healthy
    volumes:
     - ./server:/liquibase/changelog
    environment:
      INSTALL_MYSQL: true
    command: ["update", "--changelog-file=changelog/liquibaseChangeLog.sql", "--url=jdbc:mysql://pathfinder_mysql:3306/pathfinder_db?user=root&password=temporary_root"]

  