services:
  pathfinder_mysql: 
    image: mysql:latest
    container_name: pathfinder_mysql
    environment:
      MYSQL_DATABASE: pathfinder_db
    env_file: .env
    ports:
      - "3306:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=temporary_root --execute \"SHOW DATABASES;\""
      timeout: 20s
      retries: 10
    #volumes:
      #- mysql_data:/var/lib/mysql
#volumes:
  #mysql_data:
    
  liquibase:
    image: liquibase/liquibase:latest
    depends_on: 
      pathfinder_mysql:
        condition: 
         service_healthy
    volumes:
     - ./server:/liquibase/changelog
    environment:
      INSTALL_MYSQL: true
      LIQUIBASE_DBCLHISTORY_SEVERITY: "0"
    command: [ "update", "--changelog-file=changelog/liquibaseChangeLog.sql", "--url=jdbc:mysql://pathfinder_mysql:3306/pathfinder_db?user=root&password=temporary_root" ]

  pf_server:
    # image: pf/server
    build: Dockerfile.server
    
    environment:
      DB_HOST: pathfinder_mysql
      DB_USER: pf_app
      DB_PASSWORD: temporary_pw
      DB_NAME: pathfinder_db
      DB_PORT: 3306
    # depends_on:
      # liquibase:
        # condition: service_completed_successfully
         
      
    ports:
      - "3001:3001"

  pf_client:
    
    build: Dockerfile.client
    # environment:
      # SOME_ENV: SOME_VALUE
    # depends_on:
      # liquibase:
          # condition: service_completed_successfully
    ports:
      - "3005:3005"